require('dotenv').config();

const FALLBACK_INDEX_MAP = {
  NIFTY:    { securityId: '13', exchangeSegment: 'IDX_I' },
  BANKNIFTY:{ securityId: '25', exchangeSegment: 'IDX_I' },
  SENSEX:   { securityId: '51', exchangeSegment: 'IDX_I' },
  FINNIFTY: { securityId: '27', exchangeSegment: 'IDX_I' },
};

const STRIKE_STEP = { NIFTY: 50, BANKNIFTY: 100, SENSEX: 100, FINNIFTY: 50 };

// Angel One index tokens — confirmed against Angel's own SmartAPI forum
// token-update announcement (99926xxx / 99919xxx series).
const ANGEL_INDEX_TOKENS = {
  NIFTY:    { token: '99926000', exchange: 'NSE' },
  BANKNIFTY:{ token: '99926009', exchange: 'NSE' },
  SENSEX:   { token: '99919000', exchange: 'BSE' },
  FINNIFTY: { token: '99926037', exchange: 'NSE' },
};

const TRACK_INDICES = (process.env.TRACK_INDICES || 'NIFTY,SENSEX,FINNIFTY')
  .split(',').map(s => s.trim().toUpperCase()).filter(Boolean);

function normBroker(v, fallback) {
  const s = (v || fallback).toUpperCase();
  return s === 'ANGEL' || s === 'ANGELONE' ? 'ANGEL' : 'DHAN';
}

const primaryBroker = normBroker(process.env.PRIMARY_BROKER, 'DHAN');
let secondaryBroker = normBroker(process.env.SECONDARY_BROKER, primaryBroker === 'DHAN' ? 'ANGEL' : 'DHAN');
if (secondaryBroker === primaryBroker) secondaryBroker = primaryBroker === 'DHAN' ? 'ANGEL' : 'DHAN';

module.exports = {
  broker: {
    primary: primaryBroker,     // 'DHAN' | 'ANGEL' — tried first for candles
    secondary: secondaryBroker, // the other one — tried if primary fails/empty
    dhan: {
      clientId: process.env.DHAN_CLIENT_ID || '',
      // Two ways to authenticate — give either and it works:
      //  1) DHAN_ACCESS_TOKEN directly (token generated by hand on web.dhan.co)
      //  2) DHAN_PIN + DHAN_TOTP_SECRET (auto-generates + auto-refreshes a
      //     token daily via Dhan's confirmed /app/generateAccessToken flow)
      accessToken: process.env.DHAN_ACCESS_TOKEN || '',
      pin: process.env.DHAN_PIN || '',
      totpSecret: process.env.DHAN_TOTP_SECRET || '',
      baseUrl: 'https://api.dhan.co',
      authBaseUrl: 'https://auth.dhan.co',
      renewEveryHours: parseInt(process.env.DHAN_RENEW_EVERY_HOURS || '20', 10),
    },
    angel: {
      apiKey: process.env.ANGEL_API_KEY || '',
      clientCode: process.env.ANGEL_CLIENT_CODE || '',
      password: process.env.ANGEL_PIN || '', // Angel's API field is called "password" but the value is your MPIN/PIN
      totpSecret: process.env.ANGEL_TOTP_SECRET || '',
      baseUrl: 'https://apiconnect.angelone.in',
    },
  },
  vapid: {
    publicKey: process.env.VAPID_PUBLIC_KEY || '',
    privateKey: process.env.VAPID_PRIVATE_KEY || '',
    contact: process.env.VAPID_SUBJECT || 'mailto:example@example.com',
  },
  server: {
    port: parseInt(process.env.PORT || '10000', 10),
    apiSecret: process.env.API_SECRET || null, // optional — open API if unset
    corsOrigins: process.env.CORS_ORIGINS || '*',
    logLevel: process.env.LOG_LEVEL || 'INFO',
  },
  polling: {
    intervalSeconds: parseInt(process.env.POLL_INTERVAL_SECONDS || '15', 10),
    marketHoursOnly: (process.env.MARKET_HOURS_ONLY || 'true').toLowerCase() !== 'false',
  },
  trackIndices: TRACK_INDICES,
  fallbackIndexMap: FALLBACK_INDEX_MAP,
  strikeStep: STRIKE_STEP,
  angelIndexTokens: ANGEL_INDEX_TOKENS,

  defaultStrategyConfig: {
    rsiPeriod: 5,
    rsiEmaPeriod: 5,
    rsiMidLine: 50,
    pullbackMaxRange: 15,
    pullbackMaxCandles: 6,
    emaFastPeriod: 9,
    emaSlowPeriod: 21,
    gannStep: 0.25,
    gannMaxLevel: 3,
    candleTimeframeMinutes: 3,
    strikePremiumMin: 5,
    strikePremiumMax: 30,
    colors: {
      price: '#c9ccd6', emaFast: '#26a69a', emaSlow: '#ef5350',
      rsi: '#7e57c2', rsiEma: '#ffa726', gannLines: '#42a5f5',
      dotGreen: '#2ecc71', straddle: '#26c6da', iv: '#7c4dff',
    },
    lineWidths: { price: 1.5, emaFast: 2, emaSlow: 2, rsi: 1.5, rsiEma: 1.5, gannLines: 1 },
  },
};
